/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Igra;
import domen.RezultatIgre;
import java.util.Date;
import javax.swing.JOptionPane;
import konstante.Operacije;
import kontroler.Komunikacija;
import modeli.ModelTabeleIgre;
import niti.CetvrtaNit;
import niti.DrugaNit;
import niti.PrvaNit;
import niti.TrecaNit;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Ari
 */
public class KlijentskaForma extends javax.swing.JFrame {

    PrvaNit prvaNit;
    DrugaNit drugaNit;
    TrecaNit trecaNit;
    CetvrtaNit cetvrtaNit;
    int brojPokusaja = 0;

    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Klijentska forma");
        tblRezultat.setModel(new ModelTabeleIgre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart1 = new javax.swing.JButton();
        btnStart2 = new javax.swing.JButton();
        btnStart3 = new javax.swing.JButton();
        btnStart4 = new javax.swing.JButton();
        btnPosalji = new javax.swing.JButton();
        btnStop1 = new javax.swing.JButton();
        btnStop2 = new javax.swing.JButton();
        btnStop3 = new javax.swing.JButton();
        btnStop4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPogodjeniNaMestu = new javax.swing.JLabel();
        lblPogodjeniNisuNaMestu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRezultat = new javax.swing.JTable();
        lblDrugiBroj = new javax.swing.JLabel();
        lblPrviBroj = new javax.swing.JLabel();
        lblCetvrtiBroj = new javax.swing.JLabel();
        lblTreciBroj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnStart1.setText("START-1");
        btnStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart1ActionPerformed(evt);
            }
        });

        btnStart2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnStart2.setText("START-2");
        btnStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart2ActionPerformed(evt);
            }
        });

        btnStart3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnStart3.setText("START-3");
        btnStart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart3ActionPerformed(evt);
            }
        });

        btnStart4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnStart4.setText("START-4");
        btnStart4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart4ActionPerformed(evt);
            }
        });

        btnPosalji.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnPosalji.setText("POSALJI");
        btnPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiActionPerformed(evt);
            }
        });

        btnStop1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnStop1.setText("STOP-1");
        btnStop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStop1ActionPerformed(evt);
            }
        });

        btnStop2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnStop2.setText("STOP-2");
        btnStop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStop2ActionPerformed(evt);
            }
        });

        btnStop3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnStop3.setText("STOP-3");
        btnStop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStop3ActionPerformed(evt);
            }
        });

        btnStop4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnStop4.setText("STOP-4");
        btnStop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStop4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Broj pogodjenih cifara koje JESU na svom mestu:");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Broj pogodjenih cifara koje NISU na svom mestu:");

        lblPogodjeniNaMestu.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        lblPogodjeniNisuNaMestu.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        tblRezultat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRezultat);

        lblDrugiBroj.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        lblDrugiBroj.setText("0");

        lblPrviBroj.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        lblPrviBroj.setText("0");

        lblCetvrtiBroj.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        lblCetvrtiBroj.setText("0");

        lblTreciBroj.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        lblTreciBroj.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStop1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStart2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStart3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStart4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPogodjeniNaMestu, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(lblPogodjeniNisuNaMestu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblPrviBroj)
                        .addGap(113, 113, 113)
                        .addComponent(lblDrugiBroj)
                        .addGap(114, 114, 114)
                        .addComponent(lblTreciBroj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(lblCetvrtiBroj)
                        .addGap(61, 61, 61)
                        .addComponent(btnPosalji, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStart1)
                    .addComponent(btnStart2)
                    .addComponent(btnStart3)
                    .addComponent(btnStart4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDrugiBroj)
                    .addComponent(lblPrviBroj)
                    .addComponent(lblTreciBroj)
                    .addComponent(lblCetvrtiBroj)
                    .addComponent(btnPosalji, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStop1)
                    .addComponent(btnStop2)
                    .addComponent(btnStop3)
                    .addComponent(btnStop4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblPogodjeniNaMestu))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPogodjeniNisuNaMestu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart1ActionPerformed
        if (prvaNit == null || !prvaNit.isAlive()) {
            prvaNit = new PrvaNit(lblPrviBroj);
            prvaNit.start();
        }
    }//GEN-LAST:event_btnStart1ActionPerformed

    private void btnStop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStop1ActionPerformed
        if (prvaNit != null && prvaNit.isAktivna()) {
            prvaNit.stopiraj();
        }
    }//GEN-LAST:event_btnStop1ActionPerformed

    private void btnStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart2ActionPerformed
        if (drugaNit == null || !drugaNit.isAlive()) {
            drugaNit = new DrugaNit(lblDrugiBroj);
            drugaNit.start();
        }
    }//GEN-LAST:event_btnStart2ActionPerformed

    private void btnStop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStop2ActionPerformed
        if (drugaNit != null && drugaNit.isAktivna()) {
            drugaNit.stopiraj();
        }
    }//GEN-LAST:event_btnStop2ActionPerformed

    private void btnStart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart3ActionPerformed
        if (trecaNit == null || !trecaNit.isAlive()) {
            trecaNit = new TrecaNit(lblTreciBroj);
            trecaNit.start();
        }
    }//GEN-LAST:event_btnStart3ActionPerformed

    private void btnStop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStop3ActionPerformed
        if (trecaNit != null && trecaNit.isAktivna()) {
            trecaNit.stopiraj();
        }
    }//GEN-LAST:event_btnStop3ActionPerformed

    private void btnStart4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart4ActionPerformed
        if (cetvrtaNit == null || !cetvrtaNit.isAlive()) {
            cetvrtaNit = new CetvrtaNit(lblCetvrtiBroj);
            cetvrtaNit.start();
        }
    }//GEN-LAST:event_btnStart4ActionPerformed

    private void btnStop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStop4ActionPerformed
        if (cetvrtaNit != null && cetvrtaNit.isAktivna()) {
            cetvrtaNit.stopiraj();
        }
    }//GEN-LAST:event_btnStop4ActionPerformed

    private void btnPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiActionPerformed
 
        if (daLiSuAktivneNiti()) {
            JOptionPane.showMessageDialog(this, "Morate prvo da stopirate brojeve!");
            return;
        }

        int prviBroj = Integer.parseInt(lblPrviBroj.getText());
        int drugiBroj = Integer.parseInt(lblDrugiBroj.getText());
        int treciBroj = Integer.parseInt(lblTreciBroj.getText());
        int cetvrtiBroj = Integer.parseInt(lblCetvrtiBroj.getText());

        int[] brojevi = new int[5];
        brojevi[0] = prviBroj;
        brojevi[1] = drugiBroj;
        brojevi[2] = treciBroj;
        brojevi[3] = cetvrtiBroj;
        brojevi[4] = ++brojPokusaja; // ovde sam cuvao broj pokusaja

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.POSALJI_KOMBINACIJU);
        kz.setParametar(brojevi);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        Igra igra = (Igra) so.getOdgovor();

        if (igra == null) {
            JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom slanja kombinacije...");
        } else {
            ModelTabeleIgre mt = (ModelTabeleIgre) tblRezultat.getModel();
            mt.dodajRezultat(igra);

            lblPogodjeniNaMestu.setText(String.valueOf(igra.getPogodjenihNaMestu()));
            lblPogodjeniNisuNaMestu.setText(String.valueOf(igra.getPogodjenihNisuNaMestu()));

            if (igra.getPogodjenihNaMestu() == 4) {
                JOptionPane.showMessageDialog(this, "Pronasli ste tacnu kombinaciju. Pobedili ste! "
                        + "Ako zelite da sacuvate ovu igru, to mozete uraditi na serverskoj aplikaciji.");
                System.exit(0);
            }

            if (brojPokusaja == 6) {
                JOptionPane.showMessageDialog(this, "Dostigli ste maksimalan broj pokusaja. "
                        + "Izgubili ste! Ako zelite da sacuvate ovu igru, to mozete uraditi "
                        + "na serverskoj aplikaciji.");
                System.exit(0);
            } else {
                JOptionPane.showMessageDialog(this, "Preostalo vam je " + (6 - brojPokusaja) + " "
                        + "pokusaja.");
            }

        }

    }//GEN-LAST:event_btnPosaljiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPosalji;
    private javax.swing.JButton btnStart1;
    private javax.swing.JButton btnStart2;
    private javax.swing.JButton btnStart3;
    private javax.swing.JButton btnStart4;
    private javax.swing.JButton btnStop1;
    private javax.swing.JButton btnStop2;
    private javax.swing.JButton btnStop3;
    private javax.swing.JButton btnStop4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCetvrtiBroj;
    private javax.swing.JLabel lblDrugiBroj;
    private javax.swing.JLabel lblPogodjeniNaMestu;
    private javax.swing.JLabel lblPogodjeniNisuNaMestu;
    private javax.swing.JLabel lblPrviBroj;
    private javax.swing.JLabel lblTreciBroj;
    private javax.swing.JTable tblRezultat;
    // End of variables declaration//GEN-END:variables

    private boolean daLiSuAktivneNiti() {
        if (prvaNit.isAktivna() == true || drugaNit.isAktivna() == true
                || trecaNit.isAktivna() == true || cetvrtaNit.isAktivna() == true) {
            return true;
        }
        return false;
    }

    //    private void resetujFormu() {
//
//        ModelTabeleIgre mt = (ModelTabeleIgre) tblRezultat.getModel();
//
//        lblPrviBroj.setText("0");
//        lblDrugiBroj.setText("0");
//        lblTreciBroj.setText("0");
//        lblCetvrtiBroj.setText("0");
//        lblPogodjeniNaMestu.setText("");
//        lblPogodjeniNisuNaMestu.setText("");
//        mt.getLista().clear();
//        mt.fireTableDataChanged();
//
//    }
}
