/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import javax.swing.JOptionPane;
import logika.Kontroler;
import niti.BingoNit;
import niti.PokreniServer;

/**
 *
 * @author Ari
 */
public class ServerskaForma extends javax.swing.JFrame {

    BingoNit bingoNit;
    PokreniServer pokreniServer;

    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Serverska forma");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblPrviBroj = new javax.swing.JLabel();
        lblDrugiBroj = new javax.swing.JLabel();
        lblTreciBroj = new javax.swing.JLabel();
        lblCetvrtiBroj = new javax.swing.JLabel();
        btnPokreniIgru = new javax.swing.JButton();
        btnSacuvajIgru = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miPogledaj = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lblPrviBroj.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        lblPrviBroj.setText("0");

        lblDrugiBroj.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        lblDrugiBroj.setText("0");

        lblTreciBroj.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        lblTreciBroj.setText("0");

        lblCetvrtiBroj.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        lblCetvrtiBroj.setText("0");

        btnPokreniIgru.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnPokreniIgru.setText("POKRENI IGRU");
        btnPokreniIgru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniIgruActionPerformed(evt);
            }
        });

        btnSacuvajIgru.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnSacuvajIgru.setText("SACUVAJ IGRU");
        btnSacuvajIgru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajIgruActionPerformed(evt);
            }
        });

        jMenu1.setText("Moje igre");

        miPogledaj.setText("Pogledaj");
        miPogledaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPogledajActionPerformed(evt);
            }
        });
        jMenu1.add(miPogledaj);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lblPrviBroj)
                .addGap(122, 122, 122)
                .addComponent(lblDrugiBroj)
                .addGap(112, 112, 112)
                .addComponent(lblTreciBroj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(lblCetvrtiBroj)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSacuvajIgru, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPokreniIgru, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrugiBroj)
                    .addComponent(lblPrviBroj)
                    .addComponent(lblTreciBroj)
                    .addComponent(lblCetvrtiBroj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPokreniIgru, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvajIgru, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

        // ovaj if radimo jer mozemo da pokrenemo vise puta nit
        // pokusajte bez ovoga da kliknete start vise puta, videcete ishod
        if (bingoNit == null || !bingoNit.isAlive()) {
            bingoNit = new BingoNit(lblPrviBroj, lblDrugiBroj, lblTreciBroj, lblCetvrtiBroj);
            bingoNit.start();
        }

    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // ovo radimo jer baca null pointer ako kliknemo STOP, a nit nije pokrenuta
        if (bingoNit != null) {
            bingoNit.stopirajNit();
        }
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnPokreniIgruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniIgruActionPerformed

        // ako nit nije pokrenuta, a kliknemo pokreni igru, bacice null pointer
        // zato smo uradili prvi if
        // drugi if smo uradili da bismo videli da li su brojevi stopirani, jer
        // ako nisu, moramo da stopiramo da bismo pokrenuli igru
        if (bingoNit != null) {
            if (!bingoNit.isAktivna()) {
                pokreniServer = new PokreniServer();
                pokreniServer.start();
                btnPokreniIgru.setEnabled(false);
                btnStart.setEnabled(false);
                btnStop.setEnabled(false);
                btnPokreniIgru.setText("Igra je pokrenuta!");

                int prviBroj = Integer.parseInt(lblPrviBroj.getText());
                int drugiBroj = Integer.parseInt(lblDrugiBroj.getText());
                int treciBroj = Integer.parseInt(lblTreciBroj.getText());
                int cetvrtiBroj = Integer.parseInt(lblCetvrtiBroj.getText());

                int[] dobitnaKombinacija = new int[4];
                dobitnaKombinacija[0] = prviBroj;
                dobitnaKombinacija[1] = drugiBroj;
                dobitnaKombinacija[2] = treciBroj;
                dobitnaKombinacija[3] = cetvrtiBroj;

                Kontroler.getInstance().setDobitnaKombinacijaBrojeva(dobitnaKombinacija);

            } else {
                JOptionPane.showMessageDialog(this, "Morate prvo da stopirate brojeve!");
            }
        }


    }//GEN-LAST:event_btnPokreniIgruActionPerformed

    private void miPogledajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPogledajActionPerformed
        new MojeIgre(this, true).setVisible(true);
    }//GEN-LAST:event_miPogledajActionPerformed

    private void btnSacuvajIgruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajIgruActionPerformed
        boolean uspesno = Kontroler.getInstance().sacuvajRezultat();

        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Uspesno sacuvan rezultat! Gasenje aplikacije...");
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom cuvanja rezultata... "
                    + "Pokusajte opet sledeci put.");
            System.exit(0);
        }
    }//GEN-LAST:event_btnSacuvajIgruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreniIgru;
    private javax.swing.JButton btnSacuvajIgru;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCetvrtiBroj;
    private javax.swing.JLabel lblDrugiBroj;
    private javax.swing.JLabel lblPrviBroj;
    private javax.swing.JLabel lblTreciBroj;
    private javax.swing.JMenuItem miPogledaj;
    // End of variables declaration//GEN-END:variables

}
